Constants = {})
    (Constants.PI = Math.PI);
    constants.PI2 = 2 * Math.PI;
    constants.PI_2 = Math.PI / 2;
    constants.PI_4 = Math.PI / 4;
    constants.PI_8 = Math.PI / 8;
    (Constants.C_PR = Math.PI / 180);
    (Constants.VLEV = 2);
    (Constants.EPS = 1e-7);
    (Constants.c = 0.105);
    (Constants.LN10 = Math.log(10));
    (Constants.PIOVER2 = Math.PI / 2);
    (Constants.TWOPI = 2 * Math.PI);
    (Constants.TWOTHIRD = 2 / 3);
    (Constants.ARCSECOND_RADIAN = 484813681109536e-20);
    module.exports = constants;